services:
  secretai-streamlit:
    image: ghcr.io/scrtlabs/secretai-chat:v2
    container_name: secretai_sample
    env_file:
      - .env
    volumes:
      - ./app_data:/app/data
    ports:
      - '8501:8501'
    restart: unless-stopped
