services:
  secretai-streamlit:
    # Pull the prebuilt image from GHCR (contains entrypoint.sh, app_streamlit.py, etc.)
    image: ghcr.io/scrtlabs/secretai-chat:latest
    container_name: secretai_streamlit

    # Pass API_KEY from the host environment into the container
    environment:
      - API_KEY

    # Bind-mount only ./app_data/data (host) → /app/data (container)
    # This preserves everything under /app/ (the image’s baked-in code), while
    # allowing entrypoint.sh to create /app/data/history.json and persist it.
    volumes:
      - ./app_data/data:/app/data

    # Expose Streamlit port
    ports:
      - "8501:8501"

    restart: unless-stopped