# Release: https://github.com/scrtlabs/secretai-chat-docker/releases/tag/v1.2.4
# Workflow URL: https://github.com/scrtlabs/secretai-chat-docker/actions/runs/15681147590
# Commit: https://github.com/scrtlabs/secretai-chat-docker/commit/26e0a92a7edacd22a57be375f67e34b5de288c4d
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secretai-chat-docker@sha256:493fd9940b41f958a3641dfa14e05fe514291846468378c91c54ce6c2e13329a
    ports:
      - '8000:8000'
